### ISSUE TITLE
this needs much more presets. Entire alphabets(greek and math symbols) would be nice

### ISSUE THREAD

**Issue by WeaselOnaStick** [horejsek/specialcharacters#2]

**Comment by horejsek** [comment]
That would be very long list of characters... Probably it would need to rewrite whole UI, actually everything. Update it to new Chrome API, add new features (like sync own lists over Gdrive and so on), but I don't plan to do anything new with this extension. Maybe one day when it breaks, I will rewrite it and add new features, but until then I don't have time for that.
